[package]
name = "ufdr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37.5", features = ["serialize"] }

[lib]
name = "ufdr"

[[bin]]
name = "ufdr-rs"
path = "src/main.rs"
